name: CI - Lint, Format, Types

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.github/**'
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '.github/**'

permissions:
  contents: read

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.34

      - name: Install deps (frozen)
        run: bun install --frozen-lockfile

      - name: ESLint
        run: bun run next lint

      - name: Biome format check
        run: bunx biome format --no-errors-on-unmatched --write=false .

      - name: Biome lint (no write)
        run: bunx biome lint --no-errors-on-unmatched .

      - name: Type check
        run: bun run test:types


